In [1]:
import pandas as pd

# Estimaciones y proyecciones 2002-2035, comuna y área urbana y rural
## Convertir a formato parquet
* Archivo incluye nombres de comunas en primera fila
* Archivo fuente está en formato ISO-8859-1 y no UTF-8.  Esto puede generar problemas con los caracteres especiales si no se especifica el formato de codificación

In [3]:
# Read CSV file with ISO-8859-1 encoding directly
df = pd.read_csv(
    './estimaciones-y-proyecciones-2002-2035-comuna-y-área-urbana-y-rural.csv',
    sep=';',
    encoding='ISO-8859-1',
    low_memory=False
)

df.to_parquet('./estimaciones-y-proyecciones-2002-2035-comuna-y-área-urbana-y-rural.parquet', compression='snappy')

# Estimaciones y proyecciones 2002-2035, comunasCSV, 9.32 MB

In [7]:
# Read CSV file with ISO-8859-1 encoding directly
df = pd.read_csv(
    './ine_estimaciones-y-proyecciones-2002-2035_base-2017_comunas0381d25bc2224f51b9770a705a434b74.csv',
    sep=',',
    encoding='ISO-8859-1',
    low_memory=False
)

df.to_parquet('./ine_estimaciones-y-proyecciones-2002-2035_base-2017_comunas.parquet', compression='snappy')

In [9]:
# Read CSV file with ISO-8859-1 encoding directly
df = pd.read_csv(
    './ine_estimaciones-y-proyecciones-2002-2035_base-2017_país_área_base.csv',
    sep=',',
    encoding='ISO-8859-1',
    low_memory=False
)

df.to_parquet('./ine_estimaciones-y-proyecciones-2002-2035_base-2017_país_área_base.parquet', compression='snappy')

In [8]:
df

,Region,Nombre Region,Provincia,Nombre Provincia,Comuna,Nombre Comuna,Sexo (1=Hombre 2=Mujer),Edad,Poblacion 2002,Poblacion 2003,...,Poblacion 2026,Poblacion 2027,Poblacion 2028,Poblacion 2029,Poblacion 2030,Poblacion 2031,Poblacion 2032,Poblacion 2033,Poblacion 2034,Poblacion 2035
0,1,Tarapacá,11,Iquique,1101,Iquique,1,0,1469,1395,...,1518,1500,1483,1466,1446,1441,1425,1410,1395,1378
1,1,Tarapacá,11,Iquique,1101,Iquique,1,1,1472,1379,...,1523,1507,1489,1470,1454,1434,1429,1413,1397,1383
2,1,Tarapacá,11,Iquique,1101,Iquique,1,2,1461,1377,...,1526,1509,1492,1477,1458,1440,1420,1412,1401,1383
3,1,Tarapacá,11,Iquique,1101,Iquique,1,3,1464,1376,...,1521,1508,1491,1474,1457,1439,1422,1401,1395,1380
4,1,Tarapacá,11,Iquique,1101,Iquique,1,4,1462,1382,...,1514,1503,1489,1472,1456,1438,1418,1403,1383,1376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56047,16,Ñuble,163,Punilla,16305,San Nicolás,2,76,22,24,...,53,55,57,59,62,64,67,71,73,75
56048,16,Ñuble,163,Punilla,16305,San Nicolás,2,77,22,23,...,47,49,52,54,56,58,60,63,67,68
56049,16,Ñuble,163,Punilla,16305,San Nicolás,2,78,20,22,...,43,44,47,49,50,52,55,57,59,63
56050,16,Ñuble,163,Punilla,16305,San Nicolás,2,79,19,20,...,40,43,45,47,49,51,53,55,57,60
56051,16,Ñuble,163,Punilla,16305,San Nicolás,2,80,93,98,...,312,326,342,359,377,397,417,438,461,484