In [3]:
import pandas as pd

# GDP per capita (Penn World Table)
* Source: Feenstra et al. (2015), Penn World Table (2021) – processed by Our World in Data
* Date Range:1950–2019
* Unit: international-$ in 2017 prices
* Original source link: https://www.rug.nl/ggdc/productivity/pwt/
* OWID link:https://ourworldindata.org/grapher/gdp-per-capita-penn-world-table

## Convertir to parquet format

In [4]:
# Read CSV file with ISO-8859-1 encoding directly
df = pd.read_csv(
    './gdp-per-capita-penn-world-table.csv',
    sep=',',
    #encoding='ISO-8859-1',
    low_memory=False
)

df.to_parquet('./gdp-per-capita-penn-world-table.parquet', compression='snappy')

In [5]:
df

         Entity Code  Year  GDP per capita (output, multiple price benchmarks)
0       Albania  ALB  1971                                          3159.8088
1       Albania  ALB  1972                                          3214.6665
2       Albania  ALB  1973                                          3267.8481
3       Albania  ALB  1974                                          3330.0708
4       Albania  ALB  1975                                          3385.2730
...         ...  ...   ...                                                ...
10103  Zimbabwe  ZWE  2015                                          2880.9058
10104  Zimbabwe  ZWE  2016                                          2919.6170
10105  Zimbabwe  ZWE  2017                                          3112.8750
10106  Zimbabwe  ZWE  2018                                          3007.2370
10107  Zimbabwe  ZWE  2019                                          2787.6590

[10108 rows x 4 columns]